#http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:file:./data/booksDb"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true


